# Generated by Django 6.1 on 2026-08-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
