# Generated by Django 6.1 on 2026-08-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feerecord')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
